### ISSUE TITLE
Standalone MA operation not implemented

### ISSUE THREAD

**Issue by AdamMAtWork** [Appdynamics/kubernetes-snapshot-extension#2]
When I try to run a standalone machine agent with this extension configured as indicated in the README.md file, the extension is not able to connect to the Kubernetes cluster that I'm trying to monitor.
I want to run standalone for the following reasons:
1. Running outside of the cluster seems to make more sense, in case the cluster is stopped or otherwise catastrophically disabled, I want the agent to continue reporting
2. The current instructions for deploying to a cluster include operations relying on a command named `oc` which, as far as I can tell, refers to an OpenShift command - but I'm not running in OpenShift, and don't have access to that command.
3. It looks like standalone operation is or will be part of this extension.

If I set `apiMode=server`, my machine agent produces the following message in the logs:
`[Monitor-Task-Thread2] 12 Mar 2019 18:40:17,608  INFO Utilities - K8s API client cannot be initialized form the config file /Users/adamm/.kube/config. Reason Unimplemented. Trying cluster creds`

If I set `apiMode=cluster`, and also after the above attempts fail, I get these messages (one for each **type** in the `entities` list) in the log:
```
[Monitor-Task-Thread4] 12 Mar 2019 18:40:17,610 ERROR SnapshotRunnerBase - Failed to push Deployments data
java.nio.file.NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/token
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.Files.readAllBytes(Files.java:3152)
        at io.kubernetes.client.util.ClientBuilder.cluster(ClientBuilder.java:175)
        at io.kubernetes.client.util.Config.fromCluster(Config.java:39)
        at com.appdynamics.monitors.kubernetes.Utilities.initClient(Utilities.java:396)
        at com.appdynamics.monitors.kubernetes.SnapshotTasks.DeploymentSnapshotRunner.generateDeploySnapshot(DeploymentSnapshotRunner.java:57)
        at com.appdynamics.monitors.kubernetes.SnapshotTasks.DeploymentSnapshotRunner.run(DeploymentSnapshotRunner.java:45)
        at com.appdynamics.extensions.TasksExecutionServiceProvider$1.run(TasksExecutionServiceProvider.java:30)
        at com.appdynamics.extensions.MonitorThreadPoolExecutor$2.run(MonitorThreadPoolExecutor.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by AdamMAtWork** [comment]
The problem is that my `.kube/config` token for my GKE was expired, and the underlying `io.kubernetes...GCPAuthenticator` class does not implement the `refresh()` method (that's where the **Unimplemented** Reason comes from).
Adding 'kubectl get all -v=7' to the Troubleshooting doc might help catch this problem. Also, not hiding the original exception in a sanitized info message, but an actual error message makes sense, since I configured the extension to use `server` mode explicitly, not `cluster` mode.
